# workflow with build and tests for backend and frontend
# two separate jobs for backend and frontend run in parallel

name: Java & Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-build:
    runs-on: ubuntu-latest
    name: Backend Build & Test (Maven)
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test
        run: mvn -f backend/ --batch-mode test
        continue-on-error: true

      - name: Build with Maven
        run: mvn --batch-mode package --file backend/pom.xml

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: backend/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

  frontend-test:
    runs-on: ubuntu-latest
    name: Frontend Test (Vitest)
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Run Vitest
        working-directory: frontend
        run: npm run test -- --run
