# workflow with build and tests for backend and frontend
# two separate jobs for backend and frontend run in parallel
# both jobs are using docker images instead of using github actions in dedicated steps 
# backend: maven:3.9-eclipse-temurin-17
# frontend: node:20

name: Java & Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9-eclipse-temurin-17
    name: Backend Build & Test (Maven)
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: mvn -f backend/ --batch-mode test
        continue-on-error: true

      - name: Build with Maven
        run: mvn --batch-mode package --file backend/pom.xml

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: backend/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

  frontend-test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    name: Frontend Test (Vitest)
    steps:
      - uses: actions/checkout@v3

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Run Vitest
        working-directory: frontend
        run: npm run test -- --run
